twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_5_layout.html.twig',
                      'bootstrap_5_horizontal_layout.html.twig',
                      'tailwind_2_layout.html.twig',
                      'form_div_layout.html.twig']
