controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

station_view:
    path: /station/{id}
    defaults: { _controller: StationController:Default:view }

delete_view:
    path: /remove-station/{id}
    defaults: { _controller: StationController:Default:view }
