controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

station_view:
    path: /station/{id}
    defaults: { _controller: StationController:Default:view }

delete_view:
    path: /remove-station/{id}
    defaults: { _controller: StationController:Default:view }

plug_view:
    path: /new-plug/{station_id}
    defaults: { _controller: PlugController:Default:view }

plugDetails_view:
    path: /plug/{id}
    defaults: { _controller: PlugController:Default:view }

deletePlug_view:
    path: /remove-plug/{id}
    defaults: { _controller: PlugController:Default:view }

carDetails_view:
    path: /car/{id}
    defaults: { _controller: CarController:Default:view }

deleteCar_view:
    path: /remove-car/{id}
    defaults: { _controller: CarController:Default:view }

booking_view:
    path: /booking/{car_id}
    defaults: { _controller: BookingController:Default:view }

select_plug:
    path: /add_plug/{booking_id}/{plug}
    defaults: { _controller: BookingController:Default:view }